#!/bin/bash
set -euo pipefail

LINKER_FLAGS="-Xlinker -ljemalloc"

while [[ $# -gt 0 ]]; do
    case $1 in
        --no-jemalloc )
        shift
        LINKER_FLAGS=""
        ;;
    esac
done

UNIDOC_ENABLE_INDEXSTORE=1 "${SWIFT_INSTALLATION}/bin/swift" build \
    --configuration release \
    --static-swift-stdlib \
    $LINKER_FLAGS
