#!/bin/bash

set -e

swift --version
swift build --package-path TestModules
swift package --package-path TestModules dump-package > TestModules/Package.swift.json

for output in SymbolGraphs Determinism
do
    mkdir -p TestModules/$output
    for module in Swift _Concurrency _Differentiation
    do
        swift symbolgraph-extract \
            -target x86_64-unknown-linux-gnu \
            -minimum-access-level internal \
            -output-dir TestModules/$output \
            -skip-inherited-docs \
            -emit-extension-block-symbols \
            -include-spi-symbols \
            -pretty-print \
            -module-name $module
    done
done

for include in TestModules/.build/debug/Modules
do
    for file in $include/*.swiftmodule
    do
        swift symbolgraph-extract \
            -target x86_64-unknown-linux-gnu \
            -minimum-access-level internal \
            -output-dir TestModules/SymbolGraphs \
            -skip-inherited-docs \
            -emit-extension-block-symbols \
            -include-spi-symbols \
            -pretty-print \
            -module-name $(basename $file .swiftmodule) \
            -I $include
    done
done

.build/release/ssgc -u $SWIFT_INSTALLATION \
    -n swift \
    -o TestPackages/swift.bson

for PACKAGE in swift-test swift-malibu swift-snippets swift-exportation cross-module-articles
do
    .build/release/ssgc -u $SWIFT_INSTALLATION \
        -p TestPackages/$PACKAGE \
        -o TestPackages/$PACKAGE.bson
done
