#!/bin/bash
set -e

swift --version

ssgc -u $SWIFT_INSTALLATION \
    -r https://github.com/apple/swift-atomics.git \
    -t 1.2.0 \
    -n swift-atomics \
    -o TestPackages/swift-atomics.bson

ssgc -u $SWIFT_INSTALLATION \
    -r https://github.com/apple/swift-nio.git \
    -t 2.75.0 \
    -n swift-nio \
    -o TestPackages/swift-nio.bson

ssgc -u $SWIFT_INSTALLATION \
    -r https://github.com/apple/swift-nio-ssl.git \
    -t 2.29.0 \
    -n swift-nio-ssl \
    -o TestPackages/swift-nio-ssl.bson

ssgc -u $SWIFT_INSTALLATION \
    -r https://github.com/apple/swift-async-dns-resolver.git \
    -t 0.1.2 \
    -n swift-async-dns-resolver \
    -o TestPackages/swift-async-dns-resolver.bson

ssgc -u $SWIFT_INSTALLATION \
    -r https://github.com/swiftlang/swift-syntax.git \
    -t 600.0.1 \
    -n swift-syntax \
    -o TestPackages/swift-syntax.bson

ssgc -u $SWIFT_INSTALLATION \
    -r https://github.com/pointfreeco/swift-snapshot-testing.git \
    -t 1.17.5 \
    -n swift-snapshot-testing \
    -o TestPackages/swift-snapshot-testing.bson

ssgc -u $SWIFT_INSTALLATION \
    -r https://github.com/swiftlang/indexstore-db.git \
    -t swift-6.0-RELEASE \
    -n indexstore-db \
    -o TestPackages/indexstore-db.bson \
    --Xcxx -I$SWIFT_INSTALLATION/lib/swift \
    --Xcxx -I$SWIFT_INSTALLATION/lib/swift/Block

ssgc -u $SWIFT_INSTALLATION \
    -r https://github.com/swiftlang/swift-book.git \
    -t swift-5.10-fcs \
    -b book \
    -n swift-book \
    -o TestPackages/swift-book.bson
