#!/bin/bash

set -e

swift --version
swift build \
    --package-path TestModules \
    -Xswiftc -emit-symbol-graph \
    -Xswiftc -emit-symbol-graph-dir -Xswiftc SymbolGraphs \
    -Xswiftc -symbol-graph-minimum-access-level -Xswiftc internal \
    -Xswiftc -emit-extension-block-symbols \
    -Xswiftc -include-spi-symbols \
    -Xswiftc -skip-inherited-docs \
    -Xswiftc -pretty-print

swift package --package-path TestModules dump-package > TestModules/Package.swift.json

for TARGET in Swift _Concurrency
do
    swift symbolgraph-extract \
        -target x86_64-unknown-linux-gnu \
        -minimum-access-level internal \
        -output-dir TestModules/SymbolGraphs \
        -skip-inherited-docs \
        -emit-extension-block-symbols \
        -include-spi-symbols \
        -pretty-print \
        -module-name $TARGET
done

swift symbolgraph-extract \
    -target x86_64-unknown-linux-gnu \
    -minimum-access-level internal \
    -output-dir TestModules/Determinism \
    -skip-inherited-docs \
    -emit-extension-block-symbols \
    -include-spi-symbols \
    -pretty-print \
    -module-name Swift


.build/release/ssgc -u $SWIFT_INSTALLATION \
    -n swift \
    -o TestPackages/swift.bson

for PACKAGE in swift-test swift-malibu swift-snippets swift-exportation
do
    .build/release/ssgc -u $SWIFT_INSTALLATION \
        -p TestPackages/$PACKAGE \
        -o TestPackages/$PACKAGE.bson
done
