#!/bin/bash
set -e

swift --version

ssgc slave https://github.com/apple/swift-atomics.git 1.2.0 \
    -u $SWIFT_INSTALLATION \
    -o TestPackages/swift-atomics.bson

ssgc slave https://github.com/apple/swift-nio.git 2.75.0 \
    -u $SWIFT_INSTALLATION \
    -o TestPackages/swift-nio.bson

ssgc slave https://github.com/apple/swift-nio-ssl.git 2.29.0 \
    -u $SWIFT_INSTALLATION \
    -o TestPackages/swift-nio-ssl.bson

ssgc slave https://github.com/apple/swift-async-dns-resolver.git 0.1.2 \
    -u $SWIFT_INSTALLATION \
    -o TestPackages/swift-async-dns-resolver.bson

ssgc slave https://github.com/swiftlang/swift-syntax.git 600.0.1 \
    -u $SWIFT_INSTALLATION \
    -o TestPackages/swift-syntax.bson

ssgc slave https://github.com/pointfreeco/swift-snapshot-testing.git 1.18.9 \
    -u $SWIFT_INSTALLATION \
    -o TestPackages/swift-snapshot-testing.bson

ssgc slave https://github.com/swiftlang/indexstore-db.git swift-6.1.2-RELEASE \
    -u $SWIFT_INSTALLATION \
    -o TestPackages/indexstore-db.bson \
    --Xcxx -I$SWIFT_INSTALLATION/lib/swift \
    --Xcxx -I$SWIFT_INSTALLATION/lib/swift/Block

ssgc slave https://github.com/swiftlang/swift-book.git swift-5.10-fcs \
    -u $SWIFT_INSTALLATION \
    -b book \
    -o TestPackages/swift-book.bson
