#!/bin/bash
set -e

export UNIDOC_ENABLE_INDEXSTORE=1

swift --version
swift build -c release --build-tests \
    --explicit-target-dependency-import-check=warn \
    -Xcxx -I$SWIFT_INSTALLATION/lib/swift \
    -Xcxx -I$SWIFT_INSTALLATION/lib/swift/Block

Scripts/Linux/GenerateTestSymbolGraphs

swift test -c release \
    --skip-build \
    --no-parallel \
    --skip SymbolGraphValidationTests \
    --skip SymbolGraphBuilderTests \
    --disable-testable-imports

SWT_SWIFT_ERROR_BACKTRACING_ENABLED=0 \
swift test -c release \
    --skip-build \
    --filter SymbolGraphBuilderTests

for f in .build/release/*Tests; do
    "$f"
done
