#!/bin/bash
set -e

export UNIDOC_ENABLE_INDEXSTORE=1

swift --version
swift build -c release \
    --explicit-target-dependency-import-check=error \
    --destination Scripts/Linux/x86_64/x86_64.json

Scripts/Linux/GenerateTestSymbolGraphs

swift test -c release \
    --explicit-target-dependency-import-check=error \
    --destination Scripts/Linux/x86_64/x86_64.json \
    --no-parallel \
    --skip SymbolGraphValidationTests \
    --disable-testable-imports

for f in .build/release/*Tests; do
  $f
done
