#!/bin/bash
set -euo pipefail

export UNIDOC_ENABLE_INDEXSTORE=1

swift --version
swift build -c release --build-tests \
    --explicit-target-dependency-import-check=warn

Scripts/Linux/GenerateTestSymbolGraphs

swift test -c release \
    --skip-build \
    --no-parallel \
    --skip SymbolGraphValidationTests \
    --skip SymbolGraphBuilderTests \
    --skip SymbolGraphCompilerTests \
    --disable-testable-imports

for suites in SymbolGraphBuilderTests SymbolGraphCompilerTests; do
    SWT_SWIFT_ERROR_BACKTRACING_ENABLED=0 swift test -c release \
        --skip-build \
        --no-parallel \
        --filter "$suites"
done
