#!/bin/bash
set -e

export UNIDOC_ENABLE_INDEXSTORE=1

swift --version

swift build -c release \
    --explicit-target-dependency-import-check=error \
    -Xcxx -I/usr/lib/swift \
    -Xcxx -I/usr/lib/swift/Block

./generate-test-symbolgraphs
for f in .build/release/*Tests; do
  $f
done
