#!/bin/bash

swift build --package-path TestModules
swift package --package-path TestModules dump-package > TestModules/Package.swift.json

for TARGET in Swift $(basename -a -s .build TestModules/.build/debug/*.build)
do
    swift symbolgraph-extract -I TestModules/.build/debug \
        -target x86_64-unknown-linux-gnu \
        -minimum-access-level internal \
        -output-dir TestModules/SymbolGraphs \
        -skip-inherited-docs \
        -emit-extension-block-symbols \
        -include-spi-symbols \
        -pretty-print \
        -module-name $TARGET
done
