#!/bin/bash
set -e

lessc --clean-css="--s1 --advanced --compatibility=ie8" \
    Stylesheets/Admin.less Assets/css/Admin.css \
    --source-map Assets/css/Admin.css.map

lessc --clean-css="--s1 --advanced --compatibility=ie8" \
    Stylesheets/Main.less Assets/css/Main.css \
    --source-map Assets/css/Main.css.map
