#!/bin/bash
set -e

swift --version

ssgc slave https://github.com/apple/swift-atomics.git 1.2.0 \
    -o TestPackages/swift-atomics.bson

ssgc slave https://github.com/apple/swift-nio.git 2.75.0 \
    -o TestPackages/swift-nio.bson

ssgc slave https://github.com/apple/swift-nio-ssl.git 2.29.0 \
    -o TestPackages/swift-nio-ssl.bson

ssgc slave https://github.com/apple/swift-async-dns-resolver.git 0.1.2 \
    -o TestPackages/swift-async-dns-resolver.bson

ssgc slave https://github.com/swiftlang/swift-syntax.git 600.0.1 \
    -o TestPackages/swift-syntax.bson

ssgc slave https://github.com/swiftlang/indexstore-db.git swift-6.0-RELEASE \
    -o TestPackages/indexstore-db.bson

ssgc slave https://github.com/swiftlang/swift-book.git swift-5.10-fcs \
    -b book \
    -o TestPackages/swift-book.bson
