#!/bin/bash
set -euo pipefail

LINKER_FLAGS="-Xlinker -ljemalloc"

while [[ $# -gt 0 ]]; do
    case $1 in
        --no-jemalloc )
        shift
        LINKER_FLAGS=""
        ;;
    esac
done

for product in unidoc unidoc-linkerd unidocd; do
    UNIDOC_ENABLE_INDEXSTORE=1 "${SWIFT_INSTALLATION}/bin/swift" build \
        --product "$product" \
        --configuration release \
        --static-swift-stdlib \
        $LINKER_FLAGS
done
