#!/bin/bash
set -e

SWIFTPM_SCRATCH=$1

if [ -z $SWIFTPM_SCRATCH ]; then
    echo "Usage: $0 <scratch-path> [ unidoc | unidoc-linkerd | unidocd ]"
    exit 1
else
    shift
fi

while [[ $# -gt 0 ]]; do
    case $1 in
        unidoc )
        shift
        # Note: ordering is significant as each `-C` is relative to the last.
        tar -czf unidoc.tar.gz \
            -C . $($SWIFTPM_SCRATCH/release/unidoc list-assets -p Assets/) \
            -C $SWIFTPM_SCRATCH/release unidoc
        ;;

        unidoc-linkerd | unidocd )
        tar -czf $1.tar.gz \
            -C $SWIFTPM_SCRATCH/release $1
        shift
        ;;

        * )
        echo "Unknown product: $1"
        exit 1
        ;;
    esac
done
