#!/bin/bash
set -e

export UNIDOC_ENABLE_INDEXSTORE=1

swift --version
swift build -c release \
    --explicit-target-dependency-import-check=error \
    -Xcxx -I/usr/lib/swift \
    -Xcxx -I/usr/lib/swift/Block \
    --build-tests

Scripts/GenerateTestSymbolGraphs

swift test -c release \
    --explicit-target-dependency-import-check=error \
    -Xcxx -I/usr/lib/swift \
    -Xcxx -I/usr/lib/swift/Block \
    --no-parallel \
    --skip-build \
    --skip SymbolGraphValidationTests \
    --disable-testable-imports

for f in .build/release/*Tests; do
  $f
done
