extension HTML
{
    @frozen public
    enum ContainerElement:String, Equatable, Hashable, Sendable
    {
        case html
        case head
        case body
        case a
        case abbr
        case audio
        case b
        case bdi
        case bdo
        case address
        case article
        case aside
        case blockquote
        case button
        case canvas
        case caption
        case code
        case colgroup
        case cite
        case data
        case datalist
        case del
        case details
        case dialog
        case dfn
        case div
        case dl
        case dt
        case dd
        case em
        case embed
        case fieldset
        case figcaption
        case figure
        case footer
        case form
        case h1
        case h2
        case h3
        case h4
        case h5
        case h6
        case header
        case i
        case iframe
        case ins
        case kbd
        case label
        case legend
        case li
        case main
        case map
        case mark
        case menu
        case meter
        case nav
        case noscript
        case ol
        case object
        case optgroup
        case option
        case output
        case p
        case picture
        case portal
        case pre
        case progress
        case q
        case rp
        case rt
        case ruby
        case s
        case samp
        case small
        case section
        case span
        case select
        case slot
        case strong
        case sub
        case summary
        case sup
        case table
        case tbody
        case td
        case template
        case textarea
        case tfoot
        case th
        case thead
        case time
        case title
        case tr
        case u
        case ul
        case `var`
        case video

        @available(*, unavailable)
        case script
        @available(*, unavailable)
        case style
    }
}
