name: Deploy

permissions:
    contents: write
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'The version to deploy'
                required: true
                type: string
    workflow_call:
        inputs:
            version:
                description: 'The version to deploy'
                required: true
                type: string

jobs:
    macOS:
        runs-on: macos-26
        env:
            DEPLOY_VERSION: ${{ inputs.version }}
        steps:
            -   name: 💝 Setup AWS CLI 💝
                uses: aws-actions/configure-aws-credentials@v6
                with:
                    aws-secret-access-key: ${{ secrets.AWS_S3_ACCESS_SECRET }}
                    aws-access-key-id: ${{ vars.AWS_S3_ACCESS_KEY }}
                    aws-region: us-east-1

            -   name: 💝 Checkout repository 💝
                uses: actions/checkout@v6

            -   name: 💝 Build products 💝
                env:
                    UNIDOC_ENABLE_INDEXSTORE: "1"
                run: |
                    swift --version
                    swift build -c release --product unidoc
                    Scripts/Package .build unidoc

            -   name: 💝 Upload products 💝
                run: Scripts/Deploy unidoc.tar.gz
                env:
                    DEPLOY_PLATFORM: "${{ github.job }}"

    Linux:
        strategy:
            matrix:
                arch:
                    -   id: aarch64
                    -   id: x86_64

        runs-on: ubuntu-latest
        name: "Ubuntu 24.04 (${{ matrix.arch.id }})"
        env:
            DEPLOY_VERSION: ${{ inputs.version }}
        steps:
            -   name: 💝 Setup AWS CLI 💝
                uses: aws-actions/configure-aws-credentials@v6
                with:
                    aws-secret-access-key: ${{ secrets.AWS_S3_ACCESS_SECRET }}
                    aws-access-key-id: ${{ vars.AWS_S3_ACCESS_KEY }}
                    aws-region: us-east-1

            -   name: 💝 Checkout repository 💝
                uses: actions/checkout@v6

            -   name: 💝 Build Unidoc 💝
                run: |
                    Scripts/Linux/Build ${{ matrix.arch.id }} \
                        --os noble \
                        --no-jemalloc
                    Scripts/Package .build.${{ matrix.arch.id }} \
                        unidoc

            -   name: 💝 Upload products 💝
                run: Scripts/Deploy unidoc.tar.gz
                env:
                    DEPLOY_PLATFORM: "${{ github.job }}-${{ matrix.arch.id }}"

            -   name: 💝 Update badge 💝
                uses: rarestype/rarestbadge@v1
                if: always()
                with:
                    badge: Release/${{ github.job }}-${{ matrix.arch.id }}
                    title: Release


    # the difference between this and regular Linux is it uses libjemalloc
    Linux-server:
        runs-on: ubuntu-latest
        name: "Ubuntu 24.04 (server)"
        env:
            DEPLOY_VERSION: ${{ inputs.version }}
        steps:
            -   name: 💝 Setup AWS CLI 💝
                uses: aws-actions/configure-aws-credentials@v6
                with:
                    aws-secret-access-key: ${{ secrets.AWS_S3_ACCESS_SECRET }}
                    aws-access-key-id: ${{ vars.AWS_S3_ACCESS_KEY }}
                    aws-region: us-east-1

            -   name: 💝 Checkout repository 💝
                uses: actions/checkout@v6

            -   name: 💝 Build products 💝
                run: |
                    Scripts/Linux/Build aarch64 --os noble
                    Scripts/Package .build.aarch64 \
                        unidoc-linkerd \
                        unidocd

            -   name: 💝 Upload products 💝
                run: Scripts/Deploy unidoc-linkerd.tar.gz unidocd.tar.gz
                env:
                    DEPLOY_PLATFORM: "Linux-aarch64"

            -   name: 💝 Update badge 💝
                uses: rarestype/rarestbadge@v1
                if: always()
                with:
                    badge: Release/${{ github.job }}
                    title: Release
