name: package

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-22.04
        name: Ubuntu 22.04
        env:
            UNIDOC_ENABLE_INDEXSTORE: "1"
            AWS_S3_ACCESS_SECRET: ${{ secrets.AWS_S3_ACCESS_SECRET }}
            UNIDOC_PLATFORM: "linux-$(uname -i)"
            UNIDOC_VERSION: ${{ github.head_ref || github.ref_name }}
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build release
                run: |
                    swift --version
                    swift build -c release \
                        -Xcxx -I/usr/lib/swift \
                        -Xcxx -I/usr/lib/swift/Block

            -   name: Upload binaries
                run: |
                    .build/release/unidoc-publish \
                        unidoc-tools \
                        /unidoc/$UNIDOC_VERSION/$UNIDOC_PLATFORM/unidoc \
                        --secret $AWS_S3_ACCESS_SECRET

