name: package

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04

        env:
            AWS_S3_ACCESS_SECRET: ${{ secrets.AWS_S3_ACCESS_SECRET }}

            SWIFT_PREFIX: "swift-5.10.1-release/ubuntu2404/swift-5.10.1-RELEASE"
            SWIFT_ID: "swift-5.10.1-RELEASE-ubuntu24.04"

            UNIDOC_ENABLE_INDEXSTORE: "1"
            UNIDOC_PLATFORM: "linux-$(uname -i)"
            UNIDOC_VERSION: ${{ github.head_ref || github.ref_name }}

        steps:
            -   name: Cache Swift toolchain
                uses: actions/cache@v2
                with:
                    path: ${{ env.SWIFT_ID }}.tar.gz
                    key: ${{ env.SWIFT_ID }}

            -   name: Cache status
                id:   cache_status
                uses: andstor/file-existence-action@v1
                with:
                    files: ${{ env.SWIFT_ID }}.tar.gz

            -   name: Download Swift
                if: steps.cache_status.outputs.files_exists == 'false'
                run: |
                    curl https://download.swift.org/$SWIFT_PREFIX/$SWIFT_ID.tar.gz \
                        --output $SWIFT_ID.tar.gz

            -   name: Set up Swift
                run: |
                    mkdir -p $GITHUB_WORKSPACE/$SWIFT_ID
                    tar -xzf $SWIFT_ID.tar.gz -C $GITHUB_WORKSPACE/$SWIFT_ID --strip 1
                    echo "$GITHUB_WORKSPACE/$SWIFT_ID/usr/bin" >> $GITHUB_PATH

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build release
                run: |
                    swift --version
                    swift build -c release \
                        -Xcxx -I$GITHUB_WORKSPACE/$SWIFT_ID/usr/lib/swift \
                        -Xcxx -I$GITHUB_WORKSPACE/$SWIFT_ID/usr/lib/swift/Block

            -   name: Upload binaries
                run: |
                    .build/release/unidoc-publish \
                        unidoc-tools \
                        /unidoc/$UNIDOC_VERSION/$UNIDOC_PLATFORM/unidoc \
                        --secret $AWS_S3_ACCESS_SECRET

