# This workflow builds the project for production, with IndexStoreDB integration enabled.
name: test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux-server:
        runs-on: ubuntu-24.04
        name: Linux (server)
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Set up mock deployments
                run: |
                    docker compose -f Guides/docs.docc/local/docker-compose.yml up -d

            -   name: Initialize replica set
                run: |
                    timeout 60s bash -c \
                    'until docker exec -t unidoc-mongod-container \
                    /bin/mongosh --file /unidoc-rs-init-containerized.js; do sleep 1; done'

            -   name: Run pipeline
                run: |
                    docker run -t --rm \
                        --network=unidoc-test \
                        --name swift-environment \
                        --user root \
                        -v $PWD:/swift/swift-unidoc \
                        -w /swift/swift-unidoc \
                        -e SWIFT_INSTALLATION=/usr \
                        swift:6.0.1-noble \
                        /bin/bash Scripts/TestAll

    linux:
        runs-on: macos-15
        name: Linux
        env:
            UNIDOC_ENABLE_INDEXSTORE: "1"

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build release
                run: |
                    swift --version
                    swift build -c release \
                        --product ssgc \
                        --explicit-target-dependency-import-check=error \
                        -Xcxx -I/usr/lib/swift \
                        -Xcxx -I/usr/lib/swift/Block
                    mv .build/release/ssgc /usr/bin/ssgc

            -   name: Build packages
                run: Scripts/GeneratePackageSymbolGraphs

            -   name: Validate packages
                run: |
                    swift test -c release \
                        --filter SymbolGraphValidationTests \
                        -Xcxx -I/usr/lib/swift \
                        -Xcxx -I/usr/lib/swift/Block

    macos:
        runs-on: macos-15
        name: macOS
        env:
            UNIDOC_ENABLE_INDEXSTORE: "1"

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build release
                run: |
                    swift --version
                    swift build -c release \
                        --product ssgc \
                        --explicit-target-dependency-import-check=error
                    mv .build/release/ssgc /usr/bin/ssgc

            -   name: Build packages
                run: Scripts/GeneratePackageSymbolGraphs

            -   name: Validate packages
                run: |
                    swift test -c release \
                        --filter SymbolGraphValidationTests
