# This workflow builds the project for production, with IndexStoreDB integration enabled.
name: test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux-server:
        runs-on: ubuntu-24.04
        name: Linux (server)
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Set up mock deployments
                run: |
                    docker compose -f Guides/docs.docc/local/docker-compose.yml up -d

            -   name: Initialize replica set
                run: |
                    timeout 60s bash -c \
                    'until docker exec -t unidoc-mongod-container \
                    /bin/mongosh --file /unidoc-rs-init-containerized.js; do sleep 1; done'

            -   name: Run pipeline
                run: |
                    docker run -t --rm \
                        --network=unidoc-test \
                        --name swift-environment \
                        --user root \
                        -v $PWD:/swift/swift-unidoc \
                        -w /swift/swift-unidoc \
                        -e SWIFT_INSTALLATION=/usr \
                        swift:6.0.2-noble \
                        /bin/bash Scripts/Linux/TestAll

    linux:
        runs-on: ubuntu-24.04
        name: Linux
        env:
            UNIDOC_ENABLE_INDEXSTORE: "1"

        steps:
            -   name: Install Swift
                uses: tayloraswift/swift-install-action@master
                with:
                    swift-prefix: "swift-6.0.2-release/ubuntu2404/swift-6.0.2-RELEASE"
                    swift-id: "swift-6.0.2-RELEASE-ubuntu24.04"

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build release
                run: |
                    swift --version
                    swift build -c release \
                        --build-tests \
                        --explicit-target-dependency-import-check=error \
                        -Xcxx -I$SWIFT_INSTALLATION/lib/swift \
                        -Xcxx -I$SWIFT_INSTALLATION/lib/swift/Block
                    mkdir $HOME/bin
                    mv .build/release/ssgc $HOME/bin
                    echo "$HOME/bin" >> $GITHUB_PATH

            -   name: Build packages
                run: Scripts/Linux/GeneratePackageSymbolGraphs

            -   name: Validate packages
                run: |
                    swift test -c release \
                        --skip-build \
                        --filter SymbolGraphValidationTests \
                        -Xcxx -I$SWIFT_INSTALLATION/lib/swift \
                        -Xcxx -I$SWIFT_INSTALLATION/lib/swift/Block

    macos:
        runs-on: macos-15
        name: macOS
        env:
            UNIDOC_ENABLE_INDEXSTORE: "1"

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build release
                run: |
                    swift --version
                    swift build -c release \
                        --product ssgc \
                        --explicit-target-dependency-import-check=error
                    mkdir $HOME/bin
                    mv .build/release/ssgc $HOME/bin
                    echo "$HOME/bin" >> $GITHUB_PATH

            -   name: Build packages
                run: Scripts/macOS/GeneratePackageSymbolGraphs

            -   name: Validate packages
                run: |
                    swift test -c release \
                        --filter SymbolGraphValidationTests
