# This workflow builds the project for production, with IndexStoreDB integration enabled.
name: Tests

permissions:
    contents: write
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    changes:
        runs-on: ubuntu-latest
        name: Assess changes
        steps:
            -   name: 💖 Checkout repository 💖
                uses: actions/checkout@v6

            -   name: 💖 Decide checks 💖
                uses: tj-actions/changed-files@v47
                id: changes
                with:
                    files_ignore: |
                        README.md
                        LICENSE
                        NOTICE
                        .mailmap
                        .gitignore
                        .github/FUNDING.yml
        outputs:
            code_changed: ${{ steps.changes.outputs.any_changed }}

    Linux-server:
        runs-on: ubuntu-24.04
        name: Linux (server)
        needs: changes
        if: ${{ needs.changes.outputs.code_changed == 'true' }}
        steps:
            -   name: 💖 Checkout repository 💖
                uses: actions/checkout@v6

            -   name: 💖 Set up mock deployments 💖
                run: |
                    docker compose -f Guides/docs.docc/local/docker-compose.yml up -d

            -   name: 💖 Initialize replica set 💖
                run: |
                    timeout 60s bash -c \
                    'until docker exec -t unidoc-mongod-container \
                    /bin/mongosh --file /unidoc-rs-init-containerized.js; do sleep 1; done'

            -   name: 💖 Install Swift 💖
                uses: rarestype/swift-install-action@v1
                with:
                    swift-release: 6.3-RELEASE

            -   name: 💖 Build release 💖
                run: |
                    swift --version
                    swift build -c release \
                        --build-tests \
                        --explicit-target-dependency-import-check=warn \
                        --static-swift-stdlib

            -   name: 💖 Run pipeline 💖
                run: |
                    docker run -t --rm \
                        --network=unidoc-test \
                        --name swift-environment \
                        --user root \
                        -v $PWD:/swift/unidoc \
                        -w /swift/unidoc \
                        -e SWIFT_INSTALLATION=/usr \
                        swift:6.3-noble \
                        /bin/bash "swift test -c release \
                            --skip-build \
                            --no-parallel \
                            --filter tag:database"

            -   name: 💖 Update badge 💖
                uses: rarestype/rarestbadge@v1
                if: always()
                with:
                    title: Linux

    Linux:
        runs-on: ubuntu-24.04
        name: Linux
        needs: changes
        if: ${{ needs.changes.outputs.code_changed == 'true' }}
        env:
            UNIDOC_ENABLE_INDEXSTORE: "1"

        steps:
            -   name: 💖 Checkout repository 💖
                uses: actions/checkout@v6

            -   name: 💖 Install Swift 💖
                uses: rarestype/swift-install-action@v1
                with:
                    swift-release: 6.3-RELEASE

            -   name: 💖 Check format 💖
                run: Scripts/Format

            -   name: 💖 Build release 💖
                run: |
                    swift --version
                    swift build -c release \
                        --build-tests \
                        --explicit-target-dependency-import-check=warn
                    mkdir "${HOME}/bin"
                    mv .build/release/ssgc "${HOME}/bin"
                    echo "${HOME}/bin" >> "$GITHUB_PATH"

            -   name: 💖 Smoke Test 💖
                run: |
                    swift test -c release \
                        --skip-build \
                        --no-parallel \
                        --skip SymbolGraphValidationTests \
                        --skip tag:database

            -   name: 💖 Build packages 💖
                run: Scripts/Linux/GeneratePackageSymbolGraphs

            -   name: 💖 Validate packages 💖
                run: |
                    swift test -c release \
                        --skip-build \
                        --no-parallel \
                        --filter SymbolGraphValidationTests

            -   name: 💖 Update badge 💖
                uses: rarestype/rarestbadge@v1
                if: always()

    macOS:
        runs-on: macos-26
        needs: changes
        if: ${{ needs.changes.outputs.code_changed == 'true' }}
        env:
            UNIDOC_ENABLE_INDEXSTORE: "1"

        steps:
            -   name: 💖 Checkout repository 💖
                uses: actions/checkout@v6

            -   name: 💖 Select Xcode 26.4 💖
                run: sudo xcode-select -s /Applications/Xcode_26.4.app/Contents/Developer

            -   name: 💖 Check format 💖
                run: Scripts/Format

            -   name: 💖 Build release 💖
                run: |
                    swift --version
                    swift build -c release \
                        --build-tests \
                        --explicit-target-dependency-import-check=warn
                    mkdir "${HOME}/bin"
                    mv .build/release/ssgc "${HOME}/bin"
                    echo "${HOME}/bin" >> "$GITHUB_PATH"

            -   name: 💖 Build packages 💖
                run: Scripts/macOS/GeneratePackageSymbolGraphs

            -   name: 💖 Validate packages 💖
                run: |
                    swift test -c release \
                        --skip-build \
                        --no-parallel \
                        --filter SymbolGraphValidationTests

            -   name: 💖 Update badge 💖
                uses: rarestype/rarestbadge@v1
                if: always()
